modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "portalhexaddon"
version = "${version}"
displayName = "Portal Hex Addon"
logoFile = "icon.png"
authors = "stickia"
description = '''
Portal Hex Addon addon for Hex Casting
'''

[[dependencies.portalhexaddon]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.portalhexaddon]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.portalhexaddon]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.portalhexaddon]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.portalhexaddon]]
modId = "immersive_portals"
mandatory = true
versionRange = "[${ImmPrtVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.portalhexaddon]]
modId = "hexgloop"
mandatory = true
versionRange = "[${HexGloopVersion},)"
ordering = "NONE"
side = "BOTH"
