# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: stickia
book_id: portalhexaddon:portalhexaddonbook
default_branch: main
github_repo: PortalHexAddon
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: PortalHexAddonModPlugin
hexdoc_plugin_classname: PortalHexAddonPlugin
java_lang:
    ext: java
    src: java
java_package: net/portalhexaddon
mod_display_name: Portal Hex Addon
modid: portalhexaddon
multiloader: true
package_export_root: doc/src/hexdoc_portalhexaddon/_export
package_name: hexdoc-portalhexaddon
package_slug: hexdoc_portalhexaddon
package_src: doc/src/hexdoc_portalhexaddon
pages_url: https://stickia.github.io/PortalHexAddon
pattern_regex:
    per_world_value: registerPerWorld
    regex: (?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?
pattern_registry: registry/PortalHexAddonPatternRegistry.java
