author: stickia
book_id: "portalhexaddon:portalhexaddonbook"
default_branch: main
github_repo: PortalHexAddon
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: PortalHexAddonModPlugin
hexdoc_plugin_classname: PortalHexAddonPlugin
java_lang:
  ext: java
  src: java
java_package: net/portalhexaddon
mod_display_name: Portal Hex Addon
modid: portalhexaddon
multiloader: true
pages_url: https://stickia.github.io/PortalHexAddon
pattern_regex:
  regex: '(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?'
  per_world_value: registerPerWorld
pattern_registry: registry/PortalHexAddonPatternRegistry.java
